export const images = {
    icons: {
        facebook: require('./images/facebook.png'),
        google: require('./images/google.png'),
        plus: require('./images/plus.png'),
        bookType: require('./images/BookType.png'),
        movieType: require('./images/MovieType.png'),
        gameType: require('./images/GameType.png'),
        checkIcon: require('./images/checkIcon.png'),
        chevronDown: require('./images/chevronDown.png'),
        menu: require('./images/menu.png'),
        search: require('./images/search.png'),
        plusSquare: require('./images/plus-square.png'),
        home: require('./images/home.png'),
        settings: require('./images/settings.png'),
        bell: require('./images/bell.png'),
        user: require('./images/user.png'),
        eye: require('./images/eye.png'),
    },
    images: {
        ex1: require('./images/imgExample.png'),
        ex2: require('./images/imgExample2.png'),
        ex3: require('./images/imgExample3.png'),
    },
};
